//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Continuum.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentResult
    {
        public int Id { get; set; }
        public int AssessmentId { get; set; }
        public string Rating { get; set; }
        public int DimensionId { get; set; }
    
        public virtual Dimension Dimension { get; set; }
    }
}
