//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Continuum.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        public Assessment()
        {
            this.AssessmentItems = new HashSet<AssessmentItem>();
            this.AssessmentResults = new HashSet<AssessmentResult>();
        }
    
        public int Id { get; set; }
        public int AssessmentStatusId { get; set; }
        public int TeamId { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual AssessmentStatus Status { get; set; }
        public virtual Team Team { get; set; }
        public virtual ICollection<AssessmentItem> AssessmentItems { get; set; }
        public virtual ICollection<AssessmentResult> AssessmentResults { get; set; }
    }
}
