//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Continuum.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContinuumDataContainer : DbContext
    {
        public ContinuumDataContainer()
            : base("name=ContinuumDataContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dimension> Dimensions { get; set; }
        public virtual DbSet<Capability> Capabilities { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<Organisation> Organisations { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<Lookup> Lookups { get; set; }
        public virtual DbSet<Goal> Goals { get; set; }
        public virtual DbSet<AssessmentItem> AssessmentItems { get; set; }
        public virtual DbSet<TeamMember> TeamMembers { get; set; }
        public virtual DbSet<AssessmentResult> AssessmentResults { get; set; }
        public virtual DbSet<CapabilityRequirement> CapabilityRequirements { get; set; }
    }
}
