//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Continuum.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMember
    {
        public TeamMember()
        {
            this.AssessmentItems = new HashSet<AssessmentItem>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public int TeamId { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual ICollection<AssessmentItem> AssessmentItems { get; set; }
    }
}
