//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Continuum.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Assessments = new HashSet<Assessment>();
            this.Goals = new HashSet<Goal>();
            this.TeamMembers = new HashSet<TeamMember>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int OrganisationId { get; set; }
        public int AvatarTypeId { get; set; }
    
        public virtual Organisation Organisation { get; set; }
        public virtual ICollection<Assessment> Assessments { get; set; }
        public virtual ICollection<Goal> Goals { get; set; }
        public virtual ICollection<TeamMember> TeamMembers { get; set; }
        public virtual AvatarType AvatarType { get; set; }
    }
}
